$core="C:\Dev\coreclr_nano_tp4"

csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:"TRACE;DEBUG" /highentropyva+ /debug+ /debug:full /filealign:512 /optimize- `
		/r:$core\mscorlib.ni.dll `
		/r:$core\System.Core.dll `
		/r:$core\System.Collections.NonGeneric.dll `
		/r:$core\System.Runtime.Extensions.dll `
		/r:$core\System.Runtime.Serialization.Primitives.dll `
		/r:$core\System.Globalization.Extensions.dll `
		/r:$core\System.Globalization.dll `
		/r:$core\System.Collections.dll `
		/r:$core\System.Linq.dll `
		/r:$core\System.dll `
		/r:$core\System.Diagnostics.Contracts.dll `
		/r:$core\System.Runtime.Serialization.dll `
		/r:$core\System.Net.dll `
		/r:$core\System.Text.RegularExpressions.dll `
		/r:$core\System.Diagnostics.Tools.dll `
		/r:$core\System.Runtime.dll `
		/r:$core\System.ComponentModel.dll `
		/r:$core\System.Linq.Expressions.dll `
		/r:$core\System.Data.Common.dll `
		/r:$core\System.dll `
		/r:$core\System.Xml.dll `
		/keyfile:Formosatek-OpenSource.snk `
	    /out:DotLiquid.dll `
		/ruleset:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" `
		/subsystemversion:6.00 `
		/target:library `
		/utf8output `
		Exceptions\InterruptException.cs `
		FileSystems\EmbeddedFileSystem.cs `
		IValueTypeConvertible.cs `
		LiquidTypeAttribute.cs `
		RenderParameters.cs `
		Tags\Break.cs `
		Tags\Continue.cs `
		Tags\Raw.cs `
		Util\StrFTime.cs `
		Exceptions\ArgumentException.cs `
		Exceptions\FileSystemException.cs `
		FileSystems\BlankFileSystem.cs `
		Block.cs `
		Condition.cs `
		Context.cs `
		Document.cs `
		Drop.cs `
		Exceptions\ContextException.cs `
		Exceptions\FilterNotFoundException.cs `
		Exceptions\StackLevelException.cs `
		Exceptions\LiquidException.cs `
		FileSystems\IFileSystem.cs `
		FileSystems\LocalFileSystem.cs `
		IContextAware.cs `
		IIndexable.cs `
		ILiquidizable.cs `
		Liquid.cs `
		IRenderable.cs `
		NamingConventions\CSharpNamingConvention.cs `
		NamingConventions\INamingConvention.cs `
		NamingConventions\RubyNamingConvention.cs `
		Proc.cs `
		Properties\AssemblyInfo.cs `
		Properties\Resources.Designer.cs `
		Properties\Resources.it.Designer.cs `
		StandardFilters.cs `
		Strainer.cs `
		Tags\Assign.cs `
		Tags\Capture.cs `
		Tags\Case.cs `
		Tags\Comment.cs `
		Tags\Block.cs `
		Tags\Extends.cs `
		Tags\Html\TableRow.cs `
		Tags\Literal.cs `
		Tags\Unless.cs `
		Tags\Include.cs `
		Tags\IfChanged.cs `
		Tags\If.cs `
		Tags\For.cs `
		Tags\Cycle.cs `
		Template.cs `
		Util\EnumerableExtensionMethods.cs `
		Util\ExpressionUtility.cs `
		Util\ListExtensionMethods.cs `
		Util\ObjectExtensionMethods.cs `
		Util\Range.cs `
		Exceptions\SyntaxException.cs Tag.cs `
		Util\R.cs `
		Hash.cs `
		Util\Symbol.cs `
		Util\TypeUtility.cs `
		Util\WeakTable.cs `
		Variable.cs